---
jobs:
  linkChecker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - env:
        GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
      id: 'lychee'
      name: 'Link Checker'
      uses: 'lycheeverse/lychee-action@v1.5.4'
    - if: 'env.lychee_exit_code != 0'
      name: 'Create Issue From File'
      uses: 'peter-evans/create-issue-from-file@v4'
      with:
        assignees: 'xbtmatt'
        content-filepath: './lychee/out.md'
        labels:
        - 'report'
        - 'automated issue'
        title: 'Link Checker Report'
name: 'Link Checker'
'on':
  schedule:
  - cron: '*/5 * * * *'
permissions:
  issues: 'write'
  pull-requests: 'write'
...
